import { Router } from 'express';
import { healthRouter } from './health.js';
import organizationsRouter from '../modules/organizations/routes.js';
import locationsRouter from '../modules/locations/routes.js';
import authRouter from '../modules/identity/routes.js';
import membersRouter from '../modules/members/routes.js';
import staffRouter from '../modules/staff/routes.js';
import facilitiesRouter from '../modules/facilities/routes.js';
import activitiesRouter from '../modules/activities/routes.js';
import schedulingRouter from '../modules/scheduling/routes.js';
import bookingsRouter from '../modules/bookings/routes.js';
import membershipsRouter from '../modules/memberships/routes.js';
import passesRouter from '../modules/passes/routes.js';
import paymentsRouter from '../modules/payments/routes.js';
import attendanceRouter from '../modules/attendance/routes.js';
import crmRouter from '../modules/crm/routes.js';
import messagingRouter from '../modules/messaging/routes.js';
import automationRouter from '../modules/automation/routes.js';
import analyticsRouter from '../modules/analytics/routes.js';
import integrationsRouter from '../modules/integrations/routes.js';
import auditRouter from '../modules/audit/routes.js';
import billingRouter from '../modules/billing/routes.js';
import reportsRouter from '../modules/reports/routes.js';

export const router = Router();

router.use('/health', healthRouter);
router.use('/auth', authRouter);
router.use('/organizations', organizationsRouter);
router.use('/locations', locationsRouter);
router.use('/members', membersRouter);
router.use('/staff', staffRouter);
router.use('/facilities', facilitiesRouter);
router.use('/activities', activitiesRouter);
router.use('/scheduling', schedulingRouter);
router.use('/bookings', bookingsRouter);
router.use('/memberships', membershipsRouter);
router.use('/passes', passesRouter);
router.use('/payments', paymentsRouter);
router.use('/attendance', attendanceRouter);
router.use('/crm', crmRouter);
router.use('/messages', messagingRouter);
router.use('/automation', automationRouter);
router.use('/analytics', analyticsRouter);
router.use('/integrations', integrationsRouter);
router.use('/audit', auditRouter);
router.use('/billing', billingRouter);
router.use('/reports', reportsRouter);
